security:
  user:
    name: oliver
    password: pass
    role: ADMINISTRADOR
server:
  context-path: /veterinaria
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost/veterinaria?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  thymeleaf:
    cache: 'false'
